In [2]:
import numpy as np

In [3]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((10,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [7]:
np.threes(3)

AttributeError: module 'numpy' has no attribute 'threes'

In [8]:
rand(3,2)

NameError: name 'rand' is not defined

In [10]:
random.rand(3,2)

NameError: name 'random' is not defined

In [12]:
np.random.rand((3,2), dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [14]:
np.random.rand(5)

array([0.58043619, 0.15809745, 0.75586592, 0.78398977, 0.73829303])

In [15]:
np.random.rand(3,6)

array([[0.19717115, 0.64302519, 0.46142508, 0.45245638, 0.41862856,
        0.9941185 ],
       [0.08166194, 0.53418802, 0.18242279, 0.33637701, 0.16976037,
        0.74409692],
       [0.17716686, 0.1629589 , 0.08895944, 0.64623025, 0.51457109,
        0.41960091]])

In [20]:
np.random.randint(1,6)

3

In [23]:
np.random.randint(000000,999999,1) # for 6 digit otp

array([543433], dtype=int32)

In [25]:
np.random.randint(10,40,(10,10)) #4*4 matrix

array([[22, 32, 21, 21, 38, 20, 25, 15, 10, 39],
       [31, 20, 17, 24, 28, 27, 21, 14, 35, 14],
       [24, 23, 23, 24, 26, 22, 37, 25, 22, 14],
       [28, 20, 14, 33, 13, 21, 21, 15, 32, 15],
       [21, 15, 19, 37, 19, 17, 39, 23, 35, 14],
       [39, 28, 21, 39, 11, 15, 30, 22, 37, 34],
       [12, 21, 27, 25, 20, 28, 32, 16, 14, 27],
       [36, 25, 34, 12, 18, 17, 10, 29, 25, 37],
       [31, 35, 17, 16, 16, 23, 39, 30, 11, 23],
       [24, 21, 11, 33, 12, 36, 23, 12, 33, 13]], dtype=int32)

In [26]:
np.random.randint(10,40,(10,40))

array([[37, 22, 29, 26, 37, 37, 31, 37, 24, 25, 13, 18, 34, 17, 15, 16,
        30, 32, 36, 35, 26, 32, 20, 33, 26, 37, 37, 33, 15, 32, 39, 13,
        37, 22, 34, 18, 16, 15, 22, 20],
       [23, 37, 14, 35, 22, 28, 19, 10, 24, 16, 24, 25, 30, 33, 17, 34,
        35, 22, 24, 20, 20, 25, 31, 21, 23, 34, 37, 18, 15, 22, 37, 36,
        11, 10, 24, 29, 23, 31, 34, 24],
       [13, 32, 21, 14, 20, 23, 22, 16, 15, 14, 12, 15, 16, 25, 22, 14,
        31, 39, 27, 18, 22, 11, 23, 37, 32, 11, 19, 21, 19, 38, 31, 21,
        37, 24, 32, 28, 36, 20, 30, 39],
       [20, 33, 38, 18, 20, 14, 22, 24, 36, 32, 38, 20, 17, 37, 18, 23,
        16, 34, 29, 15, 29, 32, 38, 22, 24, 17, 19, 16, 27, 13, 27, 29,
        15, 32, 15, 30, 20, 30, 35, 13],
       [13, 12, 19, 25, 14, 17, 37, 31, 17, 17, 17, 25, 14, 18, 14, 17,
        33, 22, 38, 38, 19, 29, 35, 26, 29, 33, 17, 19, 34, 27, 34, 25,
        17, 17, 18, 37, 32, 17, 16, 20],
       [17, 18, 15, 16, 12, 19, 16, 18, 28, 30, 33, 15, 20, 20, 33, 39,
   

In [27]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
np.arange(1,13).reshape(5,4) # from 1-13 it is a list of 12 numbers which cannot fit into a matrix of 20 numbers.

ValueError: cannot reshape array of size 12 into shape (5,4)

SLICING IN MATRIX

In [37]:
b = np.random.randint(10,20, (5,4))
b

array([[10, 15, 11, 10],
       [16, 17, 15, 17],
       [12, 13, 13, 19],
       [17, 11, 13, 19],
       [18, 17, 17, 11]], dtype=int32)

In [38]:
type(b)

numpy.ndarray

In [39]:
b

array([[10, 15, 11, 10],
       [16, 17, 15, 17],
       [12, 13, 13, 19],
       [17, 11, 13, 19],
       [18, 17, 17, 11]], dtype=int32)

In [40]:
b[:]

array([[10, 15, 11, 10],
       [16, 17, 15, 17],
       [12, 13, 13, 19],
       [17, 11, 13, 19],
       [18, 17, 17, 11]], dtype=int32)

In [41]:
b[1:3]

array([[16, 17, 15, 17],
       [12, 13, 13, 19]], dtype=int32)

In [42]:
b

array([[10, 15, 11, 10],
       [16, 17, 15, 17],
       [12, 13, 13, 19],
       [17, 11, 13, 19],
       [18, 17, 17, 11]], dtype=int32)

In [43]:
b[1,2]

np.int32(15)

In [44]:
b[1,3]

np.int32(17)

In [45]:
b[1,-1]

np.int32(17)

In [46]:
b[2:3]

array([[12, 13, 13, 19]], dtype=int32)

In [47]:
b[0:-2]

array([[10, 15, 11, 10],
       [16, 17, 15, 17],
       [12, 13, 13, 19]], dtype=int32)

NUMPY OPERATIONS

In [52]:
arr = np.random.randint(10,20,10)

In [53]:
arr

array([11, 12, 18, 13, 15, 18, 11, 18, 10, 14], dtype=int32)

In [55]:
arr2 = np.random.randint(1,100,(10,10))

In [56]:
arr2

array([[11, 33, 52, 99, 34, 86, 53,  8,  7, 99],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35],
       [97, 27, 23, 23, 68, 40, 11, 48,  8, 91],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [91, 67, 63, 53, 40, 46, 14,  6,  6, 13],
       [29,  5, 42, 54, 54, 44, 78, 18, 20, 33],
       [68, 86, 33, 73,  7, 85, 39, 55, 42, 98],
       [73, 15, 98, 35,  3, 93, 13, 73, 65, 11],
       [40, 52,  2, 59, 68, 39, 45, 30, 66, 44],
       [ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22]], dtype=int32)

In [57]:
arr[:4]

array([11, 12, 18, 13], dtype=int32)

In [58]:
arr2[:4]

array([[11, 33, 52, 99, 34, 86, 53,  8,  7, 99],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35],
       [97, 27, 23, 23, 68, 40, 11, 48,  8, 91],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4]], dtype=int32)

In [59]:
arr2[::-4]

array([[ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22],
       [29,  5, 42, 54, 54, 44, 78, 18, 20, 33],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35]], dtype=int32)

In [60]:
arr2[::-1]

array([[ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22],
       [40, 52,  2, 59, 68, 39, 45, 30, 66, 44],
       [73, 15, 98, 35,  3, 93, 13, 73, 65, 11],
       [68, 86, 33, 73,  7, 85, 39, 55, 42, 98],
       [29,  5, 42, 54, 54, 44, 78, 18, 20, 33],
       [91, 67, 63, 53, 40, 46, 14,  6,  6, 13],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [97, 27, 23, 23, 68, 40, 11, 48,  8, 91],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35],
       [11, 33, 52, 99, 34, 86, 53,  8,  7, 99]], dtype=int32)

In [61]:
arr2[::-2]

array([[ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22],
       [73, 15, 98, 35,  3, 93, 13, 73, 65, 11],
       [29,  5, 42, 54, 54, 44, 78, 18, 20, 33],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35]], dtype=int32)

In [62]:
arr2[::-3]

array([[ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22],
       [68, 86, 33, 73,  7, 85, 39, 55, 42, 98],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [11, 33, 52, 99, 34, 86, 53,  8,  7, 99]], dtype=int32)

In [63]:
arr2[1:10:3]

array([[90, 98, 31, 85, 58, 23, 12, 53, 76, 35],
       [91, 67, 63, 53, 40, 46, 14,  6,  6, 13],
       [73, 15, 98, 35,  3, 93, 13, 73, 65, 11]], dtype=int32)

In [64]:
arr2

array([[11, 33, 52, 99, 34, 86, 53,  8,  7, 99],
       [90, 98, 31, 85, 58, 23, 12, 53, 76, 35],
       [97, 27, 23, 23, 68, 40, 11, 48,  8, 91],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [91, 67, 63, 53, 40, 46, 14,  6,  6, 13],
       [29,  5, 42, 54, 54, 44, 78, 18, 20, 33],
       [68, 86, 33, 73,  7, 85, 39, 55, 42, 98],
       [73, 15, 98, 35,  3, 93, 13, 73, 65, 11],
       [40, 52,  2, 59, 68, 39, 45, 30, 66, 44],
       [ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22]], dtype=int32)

In [65]:
arr2[0:10:3]

array([[11, 33, 52, 99, 34, 86, 53,  8,  7, 99],
       [71,  1, 58,  8, 69, 32, 13, 95, 65,  4],
       [68, 86, 33, 73,  7, 85, 39, 55, 42, 98],
       [ 8, 72, 17, 79,  3, 48, 78, 62,  5, 22]], dtype=int32)

In [66]:
arr

array([11, 12, 18, 13, 15, 18, 11, 18, 10, 14], dtype=int32)

In [67]:
arr.max()

np.int32(18)

In [68]:
arr.min()

np.int32(10)

In [69]:
arr.mean()

np.float64(14.0)

In [70]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [71]:
from numpy import *

In [72]:
a = arr

In [73]:
a

array([11, 12, 18, 13, 15, 18, 11, 18, 10, 14], dtype=int32)

In [74]:
median(a)

np.float64(13.5)

INDEXING

In [76]:
mat = np.arange(0,100).reshape(10,10)

In [77]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
row = 5
column = 5

In [79]:
row

5

In [80]:
column

5

In [81]:
mat[row,column]

np.int64(55)

In [82]:
col = 6

In [84]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [85]:
mat[row,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [89]:
mat[2:3,2:3]

array([[22]])

MASKING

In [90]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
id(mat)

2169953692400

In [92]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [93]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [94]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [95]:
mat[mat == 50]

array([50])

In [96]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])