In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

CREATING LIST

In [4]:
my_list = [0,1,2,3,4]

In [5]:
my_list

[0, 1, 2, 3, 4]

In [6]:
type(my_list)

list

CONVERTING List into Array

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10)

array([], dtype=int64)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [18]:
np.arange(10,20,5,8)

TypeError: Cannot interpret '8' as a data type

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
np.zeros(5, dtype=str)

array(['', '', '', '', ''], dtype='<U1')

In [23]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [26]:
np.zeros((2,1,3), dtype=int)

array([[[0, 0, 0]],

       [[0, 0, 0]]])